name: Docs

on:
  pull_request:
  push:
    branches:
      - "develop"
  release:
    types:
      - created

env:
  UV_USE_ACTIVE_ENV: 1

jobs:
  build:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: yezz123/setup-uv@v4
        with:
          uv-version: "0.8.12"

      - name: Install package with doc dependencies
        run: |
            uv sync --group docs

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git fetch origin gh-pages:gh-pages

      - name: Dry run
        if: github.event_name == 'pull_request'
        run: |
            uv run mkdocs build

      - name: Upload and tag as latest
        if: github.ref == 'refs/heads/develop'
        run: |
            uv run mike deploy --push latest

      - name: Upload and tag as git tag
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          uv run mike deploy --push ${{ github.ref_name }}

      - name: Set default page to latest
        run: |
          uv run mike set-default --push latest
